title: Jumpstart PhalconPHP
description: Fast development web apps with CRUD code generator

url: http://phalconjumpstart.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 10

navigation:
 - title: Home
   url: /index.html
 # - title: About
 #   url: /about
 # - title: Contact
 #   url: /contact

social:
   github: nguyenducduy
   twitter: nguyenducduyit
   # facebook: brianmaierjr
   email: nguyenducduy.it@gmail.com

google_analytics: "UA-58263416-1"
