title: Jumpstart PhalconPHP
description: Fast development web apps with CRUD code generator

url: http://phalconjumpstart.com
baseurl: ""
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title/

markdown: redcarpet
highlighter: pygments
paginate: 10

navigation:
 - title: Home
   url: /index.html
 # - title: About
 #   url: /about
 # - title: Contact
 #   url: /contact

social:
   github: nguyenducduy
   twitter: nguyenducduyit
   # facebook: brianmaierjr
   email: nguyenducduy.it@gmail.com

google_analytics: "UA-55911554-1"
